name: configuration-matrix

on: 
  push:
  workflow_dispatch:

jobs:
    deploy:
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, windows-latest]
                image: [hello-world, alpine]
                exclude:
                    - os: windows-latest
                      image: alpine
                include: 
                    - os: ubuntu-latest
                      image: amd64/hello-world:latest
                    - os: ubuntu-latest
                      image: amd64/alpine:latest

                      
        runs-on: ${{ matrix.os }}
        steps:
            - name: echo docker details
              run: docker info

            - name: docker run on ${{ matrix.os }} with image ${{ matrix.image }}
              run: docker run ${{matrix.image}}

    # deploy-on-windows:
    #     runs-on: windows-latest
    #     steps:
    #         - name: echo docker details
    #           run: docker info

    #         - name: echo docker hello world
    #           run: docker run hello-world