name: First Example

on: push

jobs:
     first-job:
       runs-on: ubuntu-latest
       steps:
        - name: checkout code
          uses: actions/checkout@v7
        
        - name: welcome message & list files & show current directory & Readme file content
          run: |
            echo "Welcome to my first example"
            ls -la
            pwd
            cat README.md

      #  - name: generate ascii artwork
      #    run: cowsay -f dragon "Welcome to my first example" >> dragon.txt
          

      #  - name: list files
      #    run: ls -la

       # - name: show current directory
       #   run: pwd

       # - name: Readme file content
       #   run: cat README.md