name: Variable and Secret Example

on: 
  schedule:
    - cron: "*/5 * * * *"

env:
    DOCKER_IMAGE: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: build docker image
              run: echo docker build -t {{env.CONTAINER_REGISTRY}}/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE

            - name: docker login
              run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            - name: push docker image
              run: echo docker push {{env.CONTAINER_REGISTRY}}/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: deploy docker image
              run: echo docker run -d -p 8080:80 {{env.CONTAINER_REGISTRY}}/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE