name: Variable and Secret Example

on: 
  workflow_dispatch


#  schedule:
#    - cron: "*/5 * * * *"

env:
    DOCKER_IMAGE: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: build docker image
              run: echo docker build -t {{env.CONTAINER_REGISTRY}}/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE

            - name: docker login
              run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            - name: push docker image
              run: echo docker push {{env.CONTAINER_REGISTRY}}/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE
    deploy:
        if: github.ref == 'refs/heads/main'
        #
        needs: docker
        concurrency: 
          group: project-deploy
          # if true , any in-progress runs will be canceled and replaced with the new run
          # if false, any in-progress runs will be allowed to complete and the new run will be queued
          cancel-in-progress: false
        runs-on: ubuntu-latest
        steps:
            - name: deploy docker image
              run: echo docker run -d -p 8080:80 {{env.CONTAINER_REGISTRY}}/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE

            - name: sleep for 10 minutes
              # optional timeout for this step, if the step takes longer than 1 minute, it will be canceled
              timeout-minutes: 1
              run: sleep 600