name: filtering workflow

on:
  push:
    # optional branch filtering, only trigger the workflow if changes are pushed to the specified branches
    branches:
      - main
      - '!feature/**'
    # optional path filtering, only trigger the workflow if changes are made to the specified paths
    paths:
      - 'src/**'
      - 'docs/**'
      - '.github/workflows/workflow-filtering.yml'
  pull_request:
    types: 
      - opened
      - closed
    # optional branch filtering, only trigger the workflow if pull_requests are opened against the specified branches
    branches:
      - main
    # optional path filtering, only trigger the workflow if changes are made to the specified paths
    paths:
      - 'src/**'
      - 'docs/**'
      - '.github/workflows/workflow-filtering.yml'

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "Hello, karim!"